### ISSUE TITLE
reenabling the hook4 to lock texture orientation (American Roads)

### ISSUE THREAD

**Issue by Unlawful-Productions** [Killface1980/RoadsUnited_Core#9]
So I've had a bit of a leave of absence here, school, new job, kids, family, etc... But I've been scouring the code for the hook system. That being said, I am heavily testing this with bool checks against "instance.m_nodes.m_buffer[nodeID].Info.m_connectgroup," and there are 4 different flags for trams. The meat of the code is in renderinstancenodenew(), in the 1st and 4th if checks. The 4th one is what flips the textures around by switching the following in this snippet: (simplified)

``` C#
//From private void RenderInstanceSegmentNew()
    if(invert2)//if invert2 == true
    {
        invert2 = false;
        NetSegment Segment = instance.m_segments.m_buffer [segmentID]
        int endNode = instance.m_segments.m_buffer [segment].m_endNode;
        //endNode variable is created separately to retain the original nodeValue after reassignment
        Segment.m_endNode = Segment.m_startNode;
        Segment.m_startNode = endNode;
        Segment.m_flags |= NetSegment.Flags.Invert;// |= is bitwise OR

        int endDir = Segment.m_endDirection;
        Segment.m_endDirection = Segment.m_startDirection;
        Segment.m_startDirection = endDir;
    }
```

**Comment by tommargar** [comment]
great to see you back and doing well. 
tbh, I'm not into modding CS any more. it's too complicated, my pc is not very fast and it's rather frustrating, having to stop on all ends becaus no one can help (color changer problem, integrating a color picker for the roads, in-game menu etc.). It took me three hours into fiddling around with the mod path, as reported in the other issue. I found modding RimWorld to be more rewarding.

**Comment by tommargar** [comment]
end of development
